from __future__ import annotations

import enum


class Language(str, enum.Enum):
    ru = "ru"
    uz = "uz"


class SellerStatus(str, enum.Enum):
    pending = "pending"
    active = "active"
    blocked = "blocked"


class ProductStatus(str, enum.Enum):
    pending = "pending"  # awaiting admin moderation
    approved = "approved"
    rejected = "rejected"


class OrderStatus(str, enum.Enum):
    new = "new"
    confirmed = "confirmed"
    processing = "processing"
    shipped = "shipped"
    delivered = "delivered"
    completed = "completed"
    cancelled = "cancelled"


# Statuses that count as "successfully completed" for seller stats
COMPLETED_STATUSES = {OrderStatus.completed}
# Statuses that release/finish an order (for completion-rate math)
FINAL_STATUSES = {OrderStatus.completed, OrderStatus.cancelled}


class PaymentProvider(str, enum.Enum):
    click = "click"
    payme = "payme"
    uzum = "uzum"
    cash = "cash"  # cash on delivery / pay later (default until gateways go live)


class PaymentStatus(str, enum.Enum):
    pending = "pending"
    paid = "paid"
    failed = "failed"
    refunded = "refunded"


class DeliveryMethod(str, enum.Enum):
    delivery = "delivery"


class MessageKind(str, enum.Enum):
    question = "question"  # buyer asks about a product ("Задать вопрос")
    order = "order"  # message tied to an order
    general = "general"


class MasterStatus(str, enum.Enum):
    active = "active"
    blocked = "blocked"


class BonusStatus(str, enum.Enum):
    pending = "pending"  # from a placed order, not yet completed
    completed = "completed"  # order completed → available in balance
    rejected = "rejected"  # order cancelled → bonus voided


class PayoutStatus(str, enum.Enum):
    pending = "pending"  # generated by the 12-day cycle, awaiting admin
    paid = "paid"  # admin confirmed the bank transfer
    rejected = "rejected"  # admin rejected → amount returned to balance
