"""master role, bonuses, payouts

Revision ID: b8361fb4e708
Revises: f571df8e958f
Create Date: 2026-08-29 10:57:35.560615
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "b8361fb4e708"
down_revision: str | None = "f571df8e958f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "master_profiles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("photo", sa.String(length=512), nullable=False),
        sa.Column("address", sa.String(length=512), nullable=False),
        sa.Column("card_number", sa.String(length=32), nullable=False),
        sa.Column(
            "status",
            sa.Enum("active", "blocked", name="masterstatus", native_enum=False, length=16),
            nullable=False,
        ),
        sa.Column("balance", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("pending", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("total_earned", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("next_payout_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_master_profiles_user_id"), "master_profiles", ["user_id"], unique=True)
    op.create_table(
        "payouts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("master_id", sa.Integer(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("card_number", sa.String(length=32), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "pending", "paid", "rejected", name="payoutstatus", native_enum=False, length=16
            ),
            nullable=False,
        ),
        sa.Column("note", sa.String(length=255), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["master_id"], ["master_profiles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_payouts_master_id"), "payouts", ["master_id"], unique=False)
    op.create_table(
        "bonus_transactions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("master_id", sa.Integer(), nullable=False),
        sa.Column("order_id", sa.Integer(), nullable=True),
        sa.Column("seller_order_id", sa.Integer(), nullable=True),
        sa.Column("amount", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "pending", "completed", "rejected", name="bonusstatus", native_enum=False, length=16
            ),
            nullable=False,
        ),
        sa.Column("note", sa.String(length=255), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["master_id"], ["master_profiles.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["order_id"], ["orders.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["seller_order_id"], ["seller_orders.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_bonus_transactions_master_id"), "bonus_transactions", ["master_id"], unique=False
    )
    op.create_index(
        op.f("ix_bonus_transactions_order_id"), "bonus_transactions", ["order_id"], unique=False
    )
    op.create_index(
        op.f("ix_bonus_transactions_seller_order_id"),
        "bonus_transactions",
        ["seller_order_id"],
        unique=False,
    )
    op.add_column(
        "order_items",
        sa.Column("bonus", sa.Numeric(precision=14, scale=2), nullable=False, server_default="0"),
    )
    op.add_column(
        "products",
        sa.Column("bonus", sa.Numeric(precision=14, scale=2), nullable=False, server_default="0"),
    )
    op.add_column(
        "seller_orders",
        sa.Column(
            "bonus_total", sa.Numeric(precision=14, scale=2), nullable=False, server_default="0"
        ),
    )
    op.add_column(
        "seller_orders",
        sa.Column("bonus_settled", sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.add_column(
        "users", sa.Column("onboarded", sa.Boolean(), nullable=False, server_default=sa.false())
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "onboarded")
    op.drop_column("seller_orders", "bonus_settled")
    op.drop_column("seller_orders", "bonus_total")
    op.drop_column("products", "bonus")
    op.drop_column("order_items", "bonus")
    op.drop_index(op.f("ix_bonus_transactions_seller_order_id"), table_name="bonus_transactions")
    op.drop_index(op.f("ix_bonus_transactions_order_id"), table_name="bonus_transactions")
    op.drop_index(op.f("ix_bonus_transactions_master_id"), table_name="bonus_transactions")
    op.drop_table("bonus_transactions")
    op.drop_index(op.f("ix_payouts_master_id"), table_name="payouts")
    op.drop_table("payouts")
    op.drop_index(op.f("ix_master_profiles_user_id"), table_name="master_profiles")
    op.drop_table("master_profiles")
    # ### end Alembic commands ###
