from __future__ import annotations

# Vehicle makes (TZ §2)
TRUCK_BRANDS = [
    ("MAN", "man"),
    ("Volvo", "volvo"),
    ("DAF", "daf"),
    ("Scania", "scania"),
    ("Mercedes-Benz", "mercedes-benz"),
    ("Renault Trucks", "renault-trucks"),
    ("Iveco", "iveco"),
]

# Categories (TZ §2): (name_ru, name_uz, slug)
CATEGORIES = [
    ("Фильтры", "Filtrlar", "filtry"),
    ("Тормозная система", "Tormoz tizimi", "tormoznaya-sistema"),
    ("Подвеска", "Osma tizimi", "podveska"),
    ("Рулевое управление", "Rul boshqaruvi", "rulevoe-upravlenie"),
    ("Двигатель", "Dvigatel", "dvigatel"),
    ("Топливная система", "Yoqilg‘i tizimi", "toplivnaya-sistema"),
    ("Сцепление", "Debriyaj", "sceplenie"),
    ("Коробка передач", "Uzatmalar qutisi", "korobka-peredach"),
    ("Электрика", "Elektr jihozlari", "elektrika"),
    ("Пневматика", "Pnevmatika", "pnevmatika"),
    ("Охлаждение", "Sovutish tizimi", "ohlazhdenie"),
    ("Запчасти кабины", "Kabina ehtiyot qismlari", "zapchasti-kabiny"),
    ("Амортизаторы", "Amortizatorlar", "amortizatory"),
    ("Масла и технические жидкости", "Moylar va texnik suyuqliklar", "masla-zhidkosti"),
    ("Ремни", "Kamarlar", "remni"),
    ("Подшипники", "Podshipniklar", "podshipniki"),
    ("Датчики", "Datchiklar", "datchiki"),
    ("Другие запчасти", "Boshqa ehtiyot qismlar", "drugie"),
]

# Demo users (dev telegram ids for DEV_AUTH_BYPASS login)
DEV_ADMIN_TG = 100000001
DEV_SELLER1_TG = 100000002
DEV_SELLER2_TG = 100000003
DEV_BUYER_TG = 100000004

# Demo products: (category_slug, brand_slug, name_ru, name_uz, article, oem, part_brand, price, stock, warranty, engine)
DEMO_PRODUCTS = [
    (
        "filtry",
        "man",
        "Масляный фильтр MANN",
        "MANN moy filtri",
        "W1170",
        "51.10100-6126",
        "MANN",
        150000,
        25,
        "6 мес",
        "D2066",
    ),
    (
        "filtry",
        "man",
        "Масляный фильтр Bosch",
        "Bosch moy filtri",
        "P7131",
        "51.10100-6126",
        "Bosch",
        135000,
        40,
        "6 мес",
        "D2066",
    ),
    (
        "filtry",
        "volvo",
        "Топливный фильтр Volvo",
        "Volvo yoqilg‘i filtri",
        "FF5320",
        "20998367",
        "Fleetguard",
        210000,
        15,
        "12 мес",
        "D13",
    ),
    (
        "tormoznaya-sistema",
        "scania",
        "Тормозные колодки Scania",
        "Scania tormoz kolodkalari",
        "29202",
        "1904310",
        "FEBI",
        890000,
        10,
        "12 мес",
        "",
    ),
    (
        "tormoznaya-sistema",
        "daf",
        "Тормозной диск DAF",
        "DAF tormoz diski",
        "BD1567",
        "1962632",
        "TRW",
        1250000,
        8,
        "12 мес",
        "",
    ),
    (
        "dvigatel",
        "man",
        "Прокладка ГБЦ MAN",
        "MAN GBS zichlagichi",
        "51039010217",
        "51.03901-0217",
        "Elring",
        3200000,
        5,
        "6 мес",
        "D2676",
    ),
    (
        "podveska",
        "mercedes-benz",
        "Пневморессора Mercedes",
        "Mercedes pnevmaressorasi",
        "4157N1",
        "9423200721",
        "Contitech",
        1750000,
        12,
        "12 мес",
        "",
    ),
    (
        "amortizatory",
        "volvo",
        "Амортизатор кабины Volvo",
        "Volvo kabina amortizatori",
        "SA080",
        "20889138",
        "Sachs",
        640000,
        20,
        "12 мес",
        "",
    ),
    (
        "elektrika",
        "scania",
        "Стартер Scania",
        "Scania starteri",
        "0001241014",
        "571863",
        "Bosch",
        4500000,
        4,
        "12 мес",
        "",
    ),
    (
        "masla-zhidkosti",
        "iveco",
        "Масло моторное 10W-40 20л",
        "Motor moyi 10W-40 20l",
        "OIL1040",
        "",
        "Petronas",
        980000,
        50,
        "",
        "",
    ),
    (
        "remni",
        "daf",
        "Ремень приводной DAF",
        "DAF uzatma kamari",
        "6PK1801",
        "1435102",
        "Gates",
        175000,
        30,
        "6 мес",
        "",
    ),
    (
        "podshipniki",
        "renault-trucks",
        "Подшипник ступицы Renault",
        "Renault stupitsa podshipnigi",
        "VKBA5423",
        "5001858500",
        "SKF",
        1350000,
        9,
        "12 мес",
        "",
    ),
]

# Plausible manufacturing country (ISO-ish code) per part brand, for demo seed.
PART_BRAND_COUNTRY = {
    "MANN": "de",
    "Bosch": "de",
    "FEBI": "de",
    "TRW": "de",
    "Elring": "de",
    "Contitech": "de",
    "Sachs": "de",
    "Hengst": "de",
    "Textar": "de",
    "Fleetguard": "us",
    "Gates": "us",
    "SKF": "se",
    "Petronas": "my",
}

# Analog cross-references: (title, [(number, brand, is_original), ...])
ANALOG_GROUPS = [
    (
        "Масляный фильтр MAN D2066",
        [
            ("51.10100-6126", "MAN", True),
            ("W1170", "MANN", False),
            ("P7131", "Bosch", False),
            ("H200W", "Hengst", False),
        ],
    ),
    (
        "Тормозные колодки Scania",
        [
            ("1904310", "Scania", True),
            ("29202", "FEBI", False),
            ("WVA29202", "Textar", False),
        ],
    ),
]
